[build-system]
requires = ["setuptools>=61.0", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "mpr"
description = "Wrapper for MicroPython mpremote tool"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.8"
keywords = ["micropython", "mpremote", "webrepl", "ampy", "rshell",
  "mpfshell", "upyloader", "upydev", "thonny"]
dynamic = ["version"]
dependencies = [
  "platformdirs",
  "argparse-from-file",
  "inotify_simple; platform_system == 'Linux'",
  "importlib-metadata; python_version < '3.8'",
]

[project.optional-dependencies]
all = ["mpremote", "mpy-cross"]

[[project.authors]]
name = "Mark Blakeney"
email = "mark.blakeney@bullet-systems.net"

[project.urls]
Homepage = "https://github.com/bulletmark/mpr"

[project.scripts]
mpr = "mpr.main:main"

[tool.setuptools_scm]
version_scheme = "post-release"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
ignore = ["SIM115", "SIM905", "BLE001", "PLW1510"]

# vim:se sw=2:
